from safenet.models import Bookings, ECommerce, Entertainment, Games, Illegal, Messaging, News, SocialMedia

t = Bookings(urlid='B001', name='BookMyShow', url='https://in.bookmyshow.com/')
t.save()
t = Bookings(urlid='B002', name='RedBus', url='https://www.redbus.in/')
t.save()
t = Bookings(urlid='B003', name='MakeMyTrip', url='https://www.makemytrip.com/')
t.save()
t = Bookings(urlid='B004', name='IRCTC', url='https://www.irctc.co.in/')
t.save()
t = Bookings(urlid='B005', name='Trivago', url='https://www.trivago.in/')
t.save()
t = Bookings(urlid='B006', name='Oyo', url='https://www.oyorooms.com/')
t.save()

t = ECommerce(urlid='EC001', name='Amazon', url='https://www.amazon.com/')
t.save()
t = ECommerce(urlid='EC002', name='Flipkart', url='https://www.flipkart.com/')
t.save()
t = ECommerce(urlid='EC003', name='Myntra', url='https://www.myntra.com/')
t.save()
t = ECommerce(urlid='EC004', name='Jabong', url='https://www.jabong.com/')
t.save()
t = ECommerce(urlid='EC005', name='SnapDeal', url='https://www.snapdeal.com/')
t.save()
t = ECommerce(urlid='EC006', name='SheIn', url='https://www.shein.com/')
t.save()

t = Entertainment(urlid='E001', name='Netflix', url='https://www.netflix.com/')
t.save()
t = Entertainment(urlid='E002', name='Spotify', url='https://www.spotify.com/')
t.save()
t = Entertainment(urlid='E003', name='YouTube', url='https://www.youtube.com/')
t.save()
t = Entertainment(urlid='E004', name='Prime Video', url='https://www.primevideo.com/')
t.save()
t = Entertainment(urlid='E005', name='Prime Music', url='https://www.amazon.com/music/prime/')
t.save()
t = Entertainment(urlid='E006', name='Twitch', url='https://www.twitch.com/')
t.save()

t = Games(urlid='G001', name='Kongregate', url='https://www.kongregate.com/')
t.save()
t = Games(urlid='G002', name='Free Online Games', url='https://www.freeonlinegames.com/')
t.save()
t = Games(urlid='G003', name='Pogo', url='https://www.pogo.com/')
t.save()
t = Games(urlid='G004', name='MiniClip', url='https://www.miniclip.com/')
t.save()
t = Games(urlid='G005', name='AGame', url='https://www.agame.com/')
t.save()

t = Illegal(urlid='I001', name='123Movies', url='https://123movies.cat/')
t.save()
t = Illegal(urlid='I002', name='GoMovies', url='https://www.gomovies123free.xyz/')
t.save()
t = Illegal(urlid='I003', name='Popcornflix', url='https://www.popcornflix.com/')
t.save()
t = Illegal(urlid='I004', name='Best Free Streaming', url='https://www.bestfreestreaming.com/')
t.save()

t = Messaging(urlid='M001', name='WhatsApp', url='https://web.whatsapp.com/')
t.save()
t = Messaging(urlid='M002', name='Messenger', url='https://www.messenger.com/')
t.save()
t = Messaging(urlid='M003', name='WeChat', url='https://web.wechat.com/')
t.save()
t = Messaging(urlid='M004', name='Hike', url='https://web.hike.in/')
t.save()

t = News(urlid='N001', name='Reuters', url='https://in.reuters.com/')
t.save()
t = News(urlid='N002', name='Times of India', url='https://timesofindia.indiatimes.com/')
t.save()
t = News(urlid='N003', name='The Hindu', url='https://www.thehindu.com/')
t.save()
t = News(urlid='N004', name='The New York Times', url='https://www.nytimes.com/')
t.save()
t = News(urlid='N005', name='The Washington Post', url='https://www.washingtonpost.com/')
t.save()

t = SocialMedia(urlid='S001', name='Instagram', url='https://www.instagram.com/')
t.save()
t = SocialMedia(urlid='S002', name='Facebook', url='https://www.facebook.com/')
t.save()
t = SocialMedia(urlid='S003', name='Snapchat', url='https://www.snapchat.com/')
t.save()
t = SocialMedia(urlid='S004', name='Twitter', url='https://www.twitter.com/')
t.save()
t = SocialMedia(urlid='S005', name='Reddit', url='https://www.reddit.com/')
t.save()
t = SocialMedia(urlid='S006', name='Tumblr', url='https://www.tumblr.com/')
t.save()